# Generated by Django 5.2.5 on 2025-09-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_projectsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='feasibility_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='innovation_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='relevance_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
