# Generated by Django 5.2.5 on 2025-09-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_projectsubmission_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='Submitted', max_length=20),
        ),
    ]
