# Generated by Django 5.2.5 on 2025-09-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile App', 'Mobile App'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science'), ('IoT', 'IoT'), ('Robotics', 'Robotics'), ('Cloud Computing', 'Cloud Computing'), ('Cybersecurity', 'Cybersecurity'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
